// bld-bridge/build.rs
//
// Generates `bld/include/bld_ffi.h` from the Rust surface when the
// `gen-headers` feature is enabled. Otherwise the file is hand-maintained
// and this build.rs is a no-op — keeping the base build dependency-free.
//
// The design choice mirrors ADR-0007's "additive-only" discipline: we
// prefer the authoritative header to be a reviewable artifact in the repo,
// not a generated byproduct. cbindgen is run in CI on a schedule to detect
// drift and post a PR comment when the header diverges.

fn main() {
    // Re-run only when the header source files change.
    println!("cargo:rerun-if-changed=../include/bld_register.h");
    println!("cargo:rerun-if-changed=../include/bld_ffi.h");
    println!("cargo:rerun-if-changed=../bld-ffi/src/lib.rs");

    #[cfg(feature = "gen-headers")]
    {
        // Placeholder for the cbindgen invocation when the feature is on.
        // Left as a doc breadcrumb; the real invocation would be:
        //
        //   let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
        //   cbindgen::Builder::new()
        //       .with_crate(crate_dir + "/../bld-ffi")
        //       .with_language(cbindgen::Language::C)
        //       .with_header(HEADER_PREAMBLE)
        //       .generate()
        //       .expect("cbindgen: bld_ffi.h")
        //       .write_to_file("../include/bld_ffi.h");
        eprintln!("bld-bridge: gen-headers feature requested but cbindgen dep is pinned off; skip");
    }
}
