//! Autogenerate `component.<Type>.{get|set}_<field>` tool entries from
//! a C++ reflection manifest (ADR-0012 §2.5).
//!
//! The C++ editor exposes `BldHostCallbacks::enumerate_components(cb, ud)`
//! (Surface P v2) which calls `cb` once per registered component with
//! the component name, stable hash, and a JSON-encoded `[{name,ty}]`
//! field list. `bld-bridge` wraps that into a typed
//! [`ComponentManifest`]; **this** module turns a manifest slice into
//! the runtime tool metadata needed by the agent and the MCP schema.
//!
//! The autogen layer does **not** emit static `ToolDescriptor` entries
//! (those need `'static` data and aren't known at compile time). Instead
//! it produces runtime [`AutogenTool`] records which the agent merges
//! into the tool catalog sent to the LLM. This keeps the static
//! inventory and the dynamic component surface cleanly separated.
//!
//! Semantics:
//!
//! * `component.<Type>.get` — one tool per component, `Read` tier.
//! * `component.<Type>.set_<field>` — one tool per (component, field)
//!   pair, `Mutate` tier. The generator skips fields whose type begins
//!   with `internal::` (engine plumbing that isn't useful to the agent).
//! * `component.<Type>.reset` — one tool per component, `Mutate` tier.
//!
//! The concrete dispatch for these tools is provided by the
//! [`BridgeDispatcher`][crate] through the generic `component.set_field` /
//! `component.get` / `component.add` entries; autogen is purely about
//! *advertising* a type-aware surface to the model.

use bld_governance::tier::Tier;
use serde::{Deserialize, Serialize};

/// One component reflected from the editor.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ComponentManifest {
    /// Component type name (e.g. `"HealthComponent"`).
    pub name: String,
    /// 64-bit stable hash the editor uses as the runtime type id.
    pub stable_hash: u64,
    /// Fields, in declaration order.
    pub fields: Vec<FieldDesc>,
}

/// A reflected field on a component.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct FieldDesc {
    /// Field name.
    pub name: String,
    /// Field type as declared in C++ (e.g. `"float"`, `"i32"`, `"Vec3"`).
    pub ty: String,
}

/// One autogenerated tool descriptor.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AutogenTool {
    /// Tool id (e.g. `"component.HealthComponent.set_hp"`).
    pub id: String,
    /// Tier (Read for `.get`, Mutate for `.set_*`/`.reset`).
    pub tier: Tier,
    /// One-line summary, markdown-safe.
    pub summary: String,
    /// JSON schema for the input (kept terse; the agent can elaborate).
    pub input_schema: serde_json::Value,
}

/// Expand one manifest into a list of tool descriptors.
pub fn expand(manifest: &ComponentManifest) -> Vec<AutogenTool> {
    let mut out = Vec::with_capacity(manifest.fields.len() + 2);

    // component.<Type>.get
    out.push(AutogenTool {
        id: format!("component.{}.get", manifest.name),
        tier: Tier::Read,
        summary: format!("Read all fields of `{}`.", manifest.name),
        input_schema: serde_json::json!({
            "type": "object",
            "required": ["handle"],
            "properties": {
                "handle": { "type": "integer", "minimum": 0 }
            }
        }),
    });

    // component.<Type>.reset
    out.push(AutogenTool {
        id: format!("component.{}.reset", manifest.name),
        tier: Tier::Mutate,
        summary: format!("Reset `{}` to its default values.", manifest.name),
        input_schema: serde_json::json!({
            "type": "object",
            "required": ["handle"],
            "properties": {
                "handle": { "type": "integer", "minimum": 0 }
            }
        }),
    });

    // component.<Type>.set_<field>
    for f in &manifest.fields {
        if f.ty.starts_with("internal::") {
            continue;
        }
        out.push(AutogenTool {
            id: format!("component.{}.set_{}", manifest.name, f.name),
            tier: Tier::Mutate,
            summary: format!(
                "Set `{}::{}` ({}) on the given entity handle.",
                manifest.name, f.name, f.ty
            ),
            input_schema: serde_json::json!({
                "type": "object",
                "required": ["handle", "value"],
                "properties": {
                    "handle": { "type": "integer", "minimum": 0 },
                    "value": json_schema_for_type(&f.ty),
                }
            }),
        });
    }

    out
}

/// Expand a slice of manifests.
pub fn expand_all(manifests: &[ComponentManifest]) -> Vec<AutogenTool> {
    manifests.iter().flat_map(expand).collect()
}

/// Parse the `fields_json` payload emitted by the editor's
/// `enumerate_components` callback into a typed
/// [`Vec<FieldDesc>`][FieldDesc]. The C++ side is expected to emit an
/// array like `[{"name":"hp","ty":"f32"}, …]`.
pub fn parse_fields_json(fields_json: &str) -> Result<Vec<FieldDesc>, String> {
    serde_json::from_str::<Vec<FieldDesc>>(fields_json).map_err(|e| e.to_string())
}

fn json_schema_for_type(ty: &str) -> serde_json::Value {
    // A short map from common C++/Rust type names to JSON schema.
    // Unknown types fall back to `{}` (any JSON).
    match ty {
        "bool" => serde_json::json!({ "type": "boolean" }),
        "i8" | "i16" | "i32" | "i64" | "u8" | "u16" | "u32" | "u64" | "int" => {
            serde_json::json!({ "type": "integer" })
        }
        "f32" | "f64" | "float" | "double" => serde_json::json!({ "type": "number" }),
        "String" | "std::string" | "string" => serde_json::json!({ "type": "string" }),
        "Vec2" => serde_json::json!({
            "type": "object",
            "required": ["x", "y"],
            "properties": {
                "x": { "type": "number" },
                "y": { "type": "number" }
            }
        }),
        "Vec3" => serde_json::json!({
            "type": "object",
            "required": ["x", "y", "z"],
            "properties": {
                "x": { "type": "number" },
                "y": { "type": "number" },
                "z": { "type": "number" }
            }
        }),
        "Color" => serde_json::json!({
            "type": "object",
            "required": ["r", "g", "b"],
            "properties": {
                "r": { "type": "number" },
                "g": { "type": "number" },
                "b": { "type": "number" },
                "a": { "type": "number" }
            }
        }),
        _ => serde_json::json!({}),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manifest(name: &str, fields: &[(&str, &str)]) -> ComponentManifest {
        ComponentManifest {
            name: name.into(),
            stable_hash: 0xdeadbeef,
            fields: fields
                .iter()
                .map(|(n, t)| FieldDesc {
                    name: (*n).into(),
                    ty: (*t).into(),
                })
                .collect(),
        }
    }

    #[test]
    fn expand_emits_get_reset_and_per_field_setter() {
        let m = manifest("HealthComponent", &[("hp", "i32"), ("max_hp", "i32")]);
        let tools = expand(&m);
        let ids: Vec<&str> = tools.iter().map(|t| t.id.as_str()).collect();
        assert!(ids.contains(&"component.HealthComponent.get"));
        assert!(ids.contains(&"component.HealthComponent.reset"));
        assert!(ids.contains(&"component.HealthComponent.set_hp"));
        assert!(ids.contains(&"component.HealthComponent.set_max_hp"));
        assert_eq!(tools.len(), 4);
    }

    #[test]
    fn get_is_read_tier_setters_are_mutate() {
        let m = manifest("X", &[("v", "f32")]);
        let tools = expand(&m);
        let g = tools.iter().find(|t| t.id.ends_with(".get")).unwrap();
        let s = tools.iter().find(|t| t.id.ends_with(".set_v")).unwrap();
        let r = tools.iter().find(|t| t.id.ends_with(".reset")).unwrap();
        assert_eq!(g.tier, Tier::Read);
        assert_eq!(s.tier, Tier::Mutate);
        assert_eq!(r.tier, Tier::Mutate);
    }

    #[test]
    fn internal_fields_are_skipped() {
        let m = manifest(
            "Engine",
            &[("frame", "u64"), ("_alloc", "internal::arena_ptr")],
        );
        let tools = expand(&m);
        let ids: Vec<&str> = tools.iter().map(|t| t.id.as_str()).collect();
        assert!(ids.contains(&"component.Engine.set_frame"));
        assert!(!ids.iter().any(|id| id.ends_with(".set__alloc")));
    }

    #[test]
    fn parse_fields_json_reads_array() {
        let js = r#"[{"name":"hp","ty":"i32"},{"name":"spd","ty":"f32"}]"#;
        let parsed = parse_fields_json(js).unwrap();
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed[0].name, "hp");
        assert_eq!(parsed[1].ty, "f32");
    }

    #[test]
    fn json_schema_vec3_has_xyz() {
        let s = json_schema_for_type("Vec3");
        assert_eq!(s.get("type").unwrap(), "object");
        let req = s.get("required").unwrap().as_array().unwrap();
        assert!(req.iter().any(|v| v.as_str() == Some("x")));
        assert!(req.iter().any(|v| v.as_str() == Some("y")));
        assert!(req.iter().any(|v| v.as_str() == Some("z")));
    }

    #[test]
    fn expand_all_flattens() {
        let a = manifest("A", &[("f", "i32")]);
        let b = manifest("B", &[("g", "f32")]);
        let tools = expand_all(&[a, b]);
        let ids: Vec<&str> = tools.iter().map(|t| t.id.as_str()).collect();
        assert!(ids.contains(&"component.A.set_f"));
        assert!(ids.contains(&"component.B.set_g"));
    }
}
